### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by merfed** [merfed/coffin2#16]
## Soil
- [ ] Select2 and Selectize to Sass (contained in select.scss right now)

## Discussion Listing
- [ ] **Sorting**
  - [ ] Post Count
  - [ ] Author
  - [ ] Responder

## Discussion
- [ ] Discussion actions: Moved to a different category. Locked, Opened, Pinned, Labels (NSFW). This can be accomplished by creating a table for discussion_actions, joining by discussion id, and including them in the comment retrieval. Order by created_at so they fall inline with the comments.
- [ ] Enemy post actions
- [ ] Hold to Delete
- [ ] Permalink quick select

## Reply and New Discussion
- [ ] Reply textarea "Edit in fullscreen"
- [ ] Preview for fortune, boon, ussr, and /me.
- [ ] Draw replies
- [x] Quick quoting, pressing r on the keyboard lets you reply to the current thread with a comment. Any selected text becomes a quote.
- [ ] **Autocomplete textarea features:**
 - [ ] @ mentions, typing @ should bring up a user list for auto complete.
 - [ ] # links, should be used to link threads with then post number. Limit to 5 at a time, get 5 most recent first, then filter as the user adds numbers.
 - [x] Integrate emoji, and have : bring up an auto complete.
  - [x] Dice rolling

## Preferences
- [ ] Upload background image.
- [ ] Allow avatars to be uploaded again without reload.
- [ ] Prevent duplicate avatars. Hash the same as images.
- [ ] Change theme.

# Account Type

**Gold Account**
- [ ] 15k points/m
- [ ] 1 Wordfilter

**Platinum Account**
- [ ] 50k points/m
- [ ] 1 Private board
- [ ] Access to all emoticons.
- [ ] 3 wordfilters.
- [ ] If u lose platinum, your board gets orphaned.

# Lumberjack
**Hive**
- [ ] Uploading an image, not an avatar.

**Points**
- [ ] Giving points to another user.

**Caretaker**
- [ ] Who puts the site into maintenance mode.
- [ ] Who takes the site out of maintenance mode.
- [ ] Who bans a user.
- [ ] Who unbans a user.
- [ ] Who makes an announcement.
- [ ] Who deletes an announcement.

# Caretaker
- [ ] In-depth analytics for pulse
- [ ] Change logo [3.0]
- [ ] Board Drag and drop sorting. [3.0]
- [ ] Show how long each maintenance mode lasted by comparing every up to the previous down. [3.0]

# Spells
- [ ] Add Hive
